### ISSUE TITLE
LoadError: cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/nmea-0.4/lib/../ext/nmea_bin

### ISSUE THREAD

**Issue by ddd1600** [maxlapshin/nmea#1]
Just downloaded the nmea gem and tried to require it in an irb console (ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]) and got this error:

```
    LoadError: cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/nmea-0.4/lib/../ext/nmea_bin
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Library/Ruby/Gems/2.0.0/gems/nmea-0.4/lib/nmea.rb:4:in `rescue in <top (required)>'
        from /Library/Ruby/Gems/2.0.0/gems/nmea-0.4/lib/nmea.rb:1:in `<top (required)>'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
        from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
        from (irb):1
        from /usr/bin/irb:12:in `<main>'
```

**Comment by ddd1600** [comment]
just installed 1.9.3 and got same error

**Comment by maxlapshin** [comment]
David, you've just got an "archeodeployer" badge =)

I haven't touched this nmea gem for many years. Frankly speaking I don't advise to use it at all, because it is using C extension with ragel parser.

Better spend 3 hours and reimplement it in Ruby. There is no use in making C ext for it.

**Comment by ddd1600** [comment]
I have a VERY BAD pseudo-gem that does this job added to my repositories. Just added it. Sort of works...
